# coding: utf-8

"""
    WSO2 API Manager - Store

    This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class APIObjectEndpointURLs(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'environment_name': 'str',
        'environment_type': 'str',
        'environment_ur_ls': 'APIObjectEnvironmentURLs'
    }

    attribute_map = {
        'environment_name': 'environmentName',
        'environment_type': 'environmentType',
        'environment_ur_ls': 'environmentURLs'
    }

    def __init__(self, environment_name=None, environment_type=None, environment_ur_ls=None):
        """
        APIObjectEndpointURLs - a model defined in Swagger
        """

        self._environment_name = None
        self._environment_type = None
        self._environment_ur_ls = None

        if environment_name is not None:
          self.environment_name = environment_name
        if environment_type is not None:
          self.environment_type = environment_type
        if environment_ur_ls is not None:
          self.environment_ur_ls = environment_ur_ls

    @property
    def environment_name(self):
        """
        Gets the environment_name of this APIObjectEndpointURLs.

        :return: The environment_name of this APIObjectEndpointURLs.
        :rtype: str
        """
        return self._environment_name

    @environment_name.setter
    def environment_name(self, environment_name):
        """
        Sets the environment_name of this APIObjectEndpointURLs.

        :param environment_name: The environment_name of this APIObjectEndpointURLs.
        :type: str
        """

        self._environment_name = environment_name

    @property
    def environment_type(self):
        """
        Gets the environment_type of this APIObjectEndpointURLs.

        :return: The environment_type of this APIObjectEndpointURLs.
        :rtype: str
        """
        return self._environment_type

    @environment_type.setter
    def environment_type(self, environment_type):
        """
        Sets the environment_type of this APIObjectEndpointURLs.

        :param environment_type: The environment_type of this APIObjectEndpointURLs.
        :type: str
        """

        self._environment_type = environment_type

    @property
    def environment_ur_ls(self):
        """
        Gets the environment_ur_ls of this APIObjectEndpointURLs.

        :return: The environment_ur_ls of this APIObjectEndpointURLs.
        :rtype: APIObjectEnvironmentURLs
        """
        return self._environment_ur_ls

    @environment_ur_ls.setter
    def environment_ur_ls(self, environment_ur_ls):
        """
        Sets the environment_ur_ls of this APIObjectEndpointURLs.

        :param environment_ur_ls: The environment_ur_ls of this APIObjectEndpointURLs.
        :type: APIObjectEnvironmentURLs
        """

        self._environment_ur_ls = environment_ur_ls

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, APIObjectEndpointURLs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
