# coding: utf-8

"""
    WSO2 API Manager - Store

    This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class APIObjectEnvironmentURLs(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'http': 'str',
        'https': 'str'
    }

    attribute_map = {
        'http': 'http',
        'https': 'https'
    }

    def __init__(self, http=None, https=None):
        """
        APIObjectEnvironmentURLs - a model defined in Swagger
        """

        self._http = None
        self._https = None

        if http is not None:
          self.http = http
        if https is not None:
          self.https = https

    @property
    def http(self):
        """
        Gets the http of this APIObjectEnvironmentURLs.
        HTTP environment URL

        :return: The http of this APIObjectEnvironmentURLs.
        :rtype: str
        """
        return self._http

    @http.setter
    def http(self, http):
        """
        Sets the http of this APIObjectEnvironmentURLs.
        HTTP environment URL

        :param http: The http of this APIObjectEnvironmentURLs.
        :type: str
        """

        self._http = http

    @property
    def https(self):
        """
        Gets the https of this APIObjectEnvironmentURLs.
        HTTPS environment URL

        :return: The https of this APIObjectEnvironmentURLs.
        :rtype: str
        """
        return self._https

    @https.setter
    def https(self, https):
        """
        Sets the https of this APIObjectEnvironmentURLs.
        HTTPS environment URL

        :param https: The https of this APIObjectEnvironmentURLs.
        :type: str
        """

        self._https = https

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, APIObjectEnvironmentURLs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
