# coding: utf-8

"""
    WSO2 API Manager - Store

    This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Application3(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'str',
        'name': 'str',
        'subscriber': 'str',
        'throttling_tier': 'str',
        'callback_url': 'str',
        'description': 'str',
        'status': 'str',
        'group_id': 'str',
        'keys': 'list[ApplicationKeyDetails]'
    }

    attribute_map = {
        'application_id': 'applicationId',
        'name': 'name',
        'subscriber': 'subscriber',
        'throttling_tier': 'throttlingTier',
        'callback_url': 'callbackUrl',
        'description': 'description',
        'status': 'status',
        'group_id': 'groupId',
        'keys': 'keys'
    }

    def __init__(self, application_id=None, name=None, subscriber=None, throttling_tier=None, callback_url=None, description=None, status='', group_id=None, keys=None):
        """
        Application3 - a model defined in Swagger
        """

        self._application_id = None
        self._name = None
        self._subscriber = None
        self._throttling_tier = None
        self._callback_url = None
        self._description = None
        self._status = None
        self._group_id = None
        self._keys = None

        if application_id is not None:
          self.application_id = application_id
        self.name = name
        if subscriber is not None:
          self.subscriber = subscriber
        self.throttling_tier = throttling_tier
        if callback_url is not None:
          self.callback_url = callback_url
        if description is not None:
          self.description = description
        if status is not None:
          self.status = status
        if group_id is not None:
          self.group_id = group_id
        if keys is not None:
          self.keys = keys

    @property
    def application_id(self):
        """
        Gets the application_id of this Application3.

        :return: The application_id of this Application3.
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """
        Sets the application_id of this Application3.

        :param application_id: The application_id of this Application3.
        :type: str
        """

        self._application_id = application_id

    @property
    def name(self):
        """
        Gets the name of this Application3.

        :return: The name of this Application3.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Application3.

        :param name: The name of this Application3.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def subscriber(self):
        """
        Gets the subscriber of this Application3.
        If subscriber is not given user invoking the API will be taken as the subscriber. 

        :return: The subscriber of this Application3.
        :rtype: str
        """
        return self._subscriber

    @subscriber.setter
    def subscriber(self, subscriber):
        """
        Sets the subscriber of this Application3.
        If subscriber is not given user invoking the API will be taken as the subscriber. 

        :param subscriber: The subscriber of this Application3.
        :type: str
        """

        self._subscriber = subscriber

    @property
    def throttling_tier(self):
        """
        Gets the throttling_tier of this Application3.

        :return: The throttling_tier of this Application3.
        :rtype: str
        """
        return self._throttling_tier

    @throttling_tier.setter
    def throttling_tier(self, throttling_tier):
        """
        Sets the throttling_tier of this Application3.

        :param throttling_tier: The throttling_tier of this Application3.
        :type: str
        """
        if throttling_tier is None:
            raise ValueError("Invalid value for `throttling_tier`, must not be `None`")

        self._throttling_tier = throttling_tier

    @property
    def callback_url(self):
        """
        Gets the callback_url of this Application3.

        :return: The callback_url of this Application3.
        :rtype: str
        """
        return self._callback_url

    @callback_url.setter
    def callback_url(self, callback_url):
        """
        Sets the callback_url of this Application3.

        :param callback_url: The callback_url of this Application3.
        :type: str
        """

        self._callback_url = callback_url

    @property
    def description(self):
        """
        Gets the description of this Application3.

        :return: The description of this Application3.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Application3.

        :param description: The description of this Application3.
        :type: str
        """

        self._description = description

    @property
    def status(self):
        """
        Gets the status of this Application3.

        :return: The status of this Application3.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Application3.

        :param status: The status of this Application3.
        :type: str
        """

        self._status = status

    @property
    def group_id(self):
        """
        Gets the group_id of this Application3.

        :return: The group_id of this Application3.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """
        Sets the group_id of this Application3.

        :param group_id: The group_id of this Application3.
        :type: str
        """

        self._group_id = group_id

    @property
    def keys(self):
        """
        Gets the keys of this Application3.

        :return: The keys of this Application3.
        :rtype: list[ApplicationKeyDetails]
        """
        return self._keys

    @keys.setter
    def keys(self, keys):
        """
        Sets the keys of this Application3.

        :param keys: The keys of this Application3.
        :type: list[ApplicationKeyDetails]
        """

        self._keys = keys

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Application3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
