# coding: utf-8

"""
    WSO2 API Manager - Store

    This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Token(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'token_scopes': 'list[str]',
        'validity_time': 'int'
    }

    attribute_map = {
        'access_token': 'accessToken',
        'token_scopes': 'tokenScopes',
        'validity_time': 'validityTime'
    }

    def __init__(self, access_token=None, token_scopes=None, validity_time=None):
        """
        Token - a model defined in Swagger
        """

        self._access_token = None
        self._token_scopes = None
        self._validity_time = None

        if access_token is not None:
          self.access_token = access_token
        if token_scopes is not None:
          self.token_scopes = token_scopes
        if validity_time is not None:
          self.validity_time = validity_time

    @property
    def access_token(self):
        """
        Gets the access_token of this Token.
        Access token

        :return: The access_token of this Token.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """
        Sets the access_token of this Token.
        Access token

        :param access_token: The access_token of this Token.
        :type: str
        """

        self._access_token = access_token

    @property
    def token_scopes(self):
        """
        Gets the token_scopes of this Token.
        Valid scopes for the access token

        :return: The token_scopes of this Token.
        :rtype: list[str]
        """
        return self._token_scopes

    @token_scopes.setter
    def token_scopes(self, token_scopes):
        """
        Sets the token_scopes of this Token.
        Valid scopes for the access token

        :param token_scopes: The token_scopes of this Token.
        :type: list[str]
        """

        self._token_scopes = token_scopes

    @property
    def validity_time(self):
        """
        Gets the validity_time of this Token.
        Maximum validity time for the access token

        :return: The validity_time of this Token.
        :rtype: int
        """
        return self._validity_time

    @validity_time.setter
    def validity_time(self, validity_time):
        """
        Sets the validity_time of this Token.
        Maximum validity time for the access token

        :param validity_time: The validity_time of this Token.
        :type: int
        """

        self._validity_time = validity_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Token):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
